# theme.toml for the Airspace Hugo theme

name = "Studio"
license = "MIT"
licenselink = "https://github.com/fushinari/studio/blob/master/LICENSE"
description = "A fork of Themefisher’s Airspace Hugo theme"
tags = ["blog",'google-analytics', 'fast', 'modern', 'minimal', 'minimalistic', 'business', 'agency-template', 'white', 'light', 'multilingual', "bootstrap", "company", "portfolio", "projects", "responsive", "themefisher", "gethugothemes"]
features = ["blog", "company", "responsive", "seo-friendly"]
min_version = "0.64.0"

[author]
  name = "Mufeed Ali"
  homepage = "https://github.com/fushinari"

[original]
  name = "Studio"
  repo = "https://github.com/fushinari/studio"
